### ISSUE TITLE
La Crosse View plugin spamming console

### ISSUE THREAD

**Issue by TillyMasters1** [GuiHash/homebridge-lacrosseview#100]
Hi, so the plugin keeps spamming my console with

```
Error while discover devices TypeError: Cannot read properties of undefined (reading 'locationId')
    at /volume1/homebridge/node_modules/homebridge-lacrosseview/src/platform.ts:117:76
    at Array.map (<anonymous>)
    at LaCrosseViewPlatform.discoverDevices (/volume1/homebridge/node_modules/homebridge-lacrosseview/src/platform.ts:117:48)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

keep in mind everything that I want is already setup but it keeps trying to "discover devices" and sending this error

**Comment by TillyMasters1** [comment]
Have you looked into this at all?
