### ISSUE TITLE
Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory

### ISSUE THREAD

**Issue by c0ldgurl** [GuiHash/homebridge-lacrosseview#6]
I'm using a Lacrosse V50 and am encountering this error message:

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: f5d43fc6-1ff9-4659-913b-ef0f72a0c43a
    at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:416:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:310:19
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:270:69)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:158:10)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)

It worked on 3 of the 4 sensors (indoor temp, indoor humidity, outdoor humidity) but failed on outdoor temperature.

After throwing this error the homebridge server entered a boot loop until I uninstalled the plugin and removed the config, and is now running normally.

I am running an older version of homebridge, v1.1.7, could that be the issue?

Even with removing the plugin and config I still see odd errors in the log:

Failed to find plugin to handle accessory Oudside Weather
Removing orphaned accessory Oudside Weather
Failed to find plugin to handle accessory Living Room
Removing orphaned accessory Living Room
Failed to find plugin to handle accessory Oudside Weather
Removing orphaned accessory Oudside Weather
Failed to find plugin to handle accessory Oudside Weather
Removing orphaned accessory Oudside Weather

I'm not sure why Oudside Weather is there 3 times but it seems to correlate with the error message above.

**Comment by c0ldgurl** [comment]
I updated to 1.3.3 and it didn't seem to help.

Here is the initial log at startup: 

[15/03/2021, 09:17:23] [LaCrosseView] New Device Online: [Outside] sensor [5152091257044992]
[15/03/2021, 09:17:23] [LaCrosseView] Adding: [Outside] sensor [5152091257044992]
[15/03/2021, 09:17:23] [LaCrosseView] New Device Online: [Living Room] sensor [6501309599055872]
[15/03/2021, 09:17:23] [LaCrosseView] Adding: [Living Room] sensor [6501309599055872]

Ten minutes later this happened:

[15/03/2021, 09:27:23] [LaCrosseView] New Device Online: [Outside] sensor [5152091257044992]
[15/03/2021, 09:27:23] [LaCrosseView] Adding: [Outside] sensor [5152091257044992]
[15/03/2021, 09:27:23] [LaCrosseView] Error while discover devices Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: f5d43fc6-1ff9-4659-913b-ef0f72a0c43a
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:564:15)
    at Bridge.Accessory.addBridgedAccessories (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:593:12)
    at BridgeService.handleRegisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/bridgeService.ts:382:17)
    at HomebridgeAPI.emit (events.js:315:20)
    at HomebridgeAPI.registerPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/api.ts:340:10)
    at LaCrosseViewPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-lacrosseview/src/platform.ts:145:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by GuiHash** [comment]
Thanks for the feedback. I currently don't have time to look at this bug now but I will definitely solve it next week.

**Comment by c0ldgurl** [comment]
Thanks! No rush.

**Comment by GuiHash** [comment]
@c0ldgurl did you try the fix ?

**Comment by c0ldgurl** [comment]
Sorry, yes I did and it’s working great!

Thanks for the plug-in!

My best
